Fix regex for pyflakes output 2.4.0
SublimeLinter/SublimeLinter-pyflakes pull request #17
Opened 2021-10-25 22:12 UTC by gorkicode

Hi! :) Greetings!

Seems that **pyflakes 2.4.0** have change their output messages format again.

In **Sublime Text Build 4113** using **SublimeLinter 4.17.0** with **SublimeLinter-pyflakes 1.3.2** and **pyflakes 2.4.0 Python 3.8.10 on Linux**

**pyflakes 2.4.0 outputs (I show you assigned as string and with escape characters):**
`bad = '<stdin>:3:9: invalid syntax\n    pass()\n        ^\n'`
`ok = "<stdin>:2:4 undefined name 'a'\n<stdin>:2:9 undefined name 'b'\n<stdin>:3:5 undefined name 'pas'\n"`

for the **bad** string the actual regex in the first capturing group **filename**:
`^(?P<filename>.+):(?P<line>\d+):((?P<col>\d+):?)?\s`
**captures** any character (the first : character too) till the integer character 3, hence filename will be '**`<stdin>:3`**' line take another value and col becomes **None** .

Then in **process_match** function (from SublimeLinter parent class)  when it try to add the marks to the view then throws:

```
SublimeLinter: #1 linter.py:1355      WARNING: pyflakes reported errors coming from '/home/dev/<stdin>:3'. However, reading that file raised:
  [Errno 2] No such file or directory: '/home/dev/<stdin>:3'.
```
Resulting in no errors displayed.
The regex for the first capturing group **filename** (#16) I think just work perfectly right now.
:grin: :+1:

2021-11-17 03:35 UTC, gorkicode reviewed
I' ve test this regex (with kaste suggested change) and one minor suggestion of mine, and works great! here the code line:
Suggested change

```diff
-        ^(?P<filename>[^:\n]+):(?P<line>\d+):((?P<col>\d+):?)?\s
+        ^(?P<filename>.+?):(?P<line>\d+):(?P<col>\d+)?:?\s
```

the last part appears more "readable" or simple to me, but works in the same manner :) (please tell me if not)

2021-11-18 21:31 UTC, kaste requested changes
The rewrite of the last part is not the same: see https://regex101.com/r/HWXdnT/1  E.g. the pathological `foo:4:: The message` would match now.   `pyflakes` will probably never output something like this but a change is not necessary either.

2022-05-15 21:24 UTC, closed without merging

2022-05-15 21:47 UTC, utkonos commented
I don't have an answer as to why this `:` is in some output and not in other output. However, looking at the source code over at pyflakes the tests show that it is there sometimes and not there other times.

Here:

https://github.com/PyCQA/pyflakes/blob/f3b1b44bf3d2d5927004fa1c2fcf1ab2def816b9/pyflakes/test/test_api.py#L507-L513

As opposed to here:

https://github.com/PyCQA/pyflakes/blob/f3b1b44bf3d2d5927004fa1c2fcf1ab2def816b9/pyflakes/test/test_api.py#L541-L546

I have tried to find where the string `invalid syntax` comes from in pyflakes and I cannot find it anywhere. Is this a message that is generated deeper down in dependencies and then wrapped by pyflakes? Are the messages that are wrapped in such a way emitted differently than the native messages?

This seems like a flaw in pyflakes that needs to be fixed, and the fix here in Sublimelinter is a downstream workaround.

Thanks for looking at this and getting it fixed and out so quickly!

2022-05-15 21:52 UTC, utkonos commented
Come to think of it: all these linters should just have an option for JSON output. That would be magical I think.